In [42]:
import pandas as pd

In [43]:
df = pd.read_excel('../data/Relatório de Produção - Completo - Dados.xlsx')

In [44]:
df

,Eficiência Geral,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,7,12,16,960,1,0.6,576,0.55,528,0,0
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,8,12,16,960,1,0.6,576,0.475,456,0,0
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,9,12,16,960,1,0.6,576,0.5,480,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,2,90,82,4920,1,0.65,3198,0.754472,3712,0,0
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,3,90,82,4920,1,0.65,3198,0.728455,3584,0,0
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,4,90,82,4920,1,0.65,3198,0.813008,4000,0,0
408,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,5,90,82,4920,1,0.65,3198,0.773984,3808,0,0
409,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,6,90,82,4920,1,0.65,3198,0.83252,4096,0,0

In [45]:
df.columns = df.iloc[1]
df = df.iloc[2:].reset_index(drop=True)
df.columns.name = None

In [46]:
df

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,7,12,16,960,1,0.6,576,0.55,528,0,0
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,8,12,16,960,1,0.6,576,0.475,456,0,0
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,9,12,16,960,1,0.6,576,0.5,480,0,0
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,10,12,16,960,1,0.6,576,0.6,576,0,0
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,11,12,16,960,1,0.6,576,0.6,576,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,2,90,82,4920,1,0.65,3198,0.754472,3712,0,0
404,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,3,90,82,4920,1,0.65,3198,0.728455,3584,0,0
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,4,90,82,4920,1,0.65,3198,0.813008,4000,0,0
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,5,90,82,4920,1,0.65,3198,0.773984,3808,0,0
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,6,90,82,4920,1,0.65,3198,0.83252,4096,0,0

In [47]:
df.columns

Index(['Data Wht (dia)', 'Forno', 'Maquina', 'Prefixo', 'OP Vertech', 'NQI',
       'Eficiencia Plan', 'Hora Hora Wht (6to6)', 'Veloc Stand', 'Veloc Real',
       'Qtd Teorica Real', 'Corte de Gota %', 'Objetivo %', 'Qtd Objetivo',
       'Empacotado %', 'Qtd Empacotado', 'Qtd Rejeicao', 'Rejeição %'],
      dtype='object')

# Percentual Objetivo

In [48]:
objetivo = df['Qtd Objetivo'].astype(float) / df['Qtd Teorica Real'].astype(float) * 100
objetivo

0      60.0
1      60.0
2      60.0
3      60.0
4      60.0
       ...
403    65.0
404    65.0
405    65.0
406    65.0
407    65.0
Length: 408, dtype: float64

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data Wht (dia)        408 non-null    object
 1   Forno                 408 non-null    str
 2   Maquina               408 non-null    str
 3   Prefixo               408 non-null    str
 4   OP Vertech            408 non-null    str
 5   NQI                   408 non-null    str
 6   Eficiencia Plan       408 non-null    str
 7   Hora Hora Wht (6to6)  408 non-null    str
 8   Veloc Stand           408 non-null    object
 9   Veloc Real            408 non-null    object
 10  Qtd Teorica Real      408 non-null    object
 11  Corte de Gota %       408 non-null    object
 12  Objetivo %            408 non-null    object
 13  Qtd Objetivo          408 non-null    object
 14  Empacotado %          408 non-null    object
 15  Qtd Empacotado        408 non-null    object
 16  Qtd Rejeicao          408 non-null    object
 17  Rejeição %            408 non-null    object
dtypes: object(11), str(7)
memory usage: 72.3+ KB

In [50]:
colunas_float = [
    "Eficiencia Plan",
    "Hora Hora Wht (6to6)",
    "Veloc Stand",
    "Veloc Real",
    "Qtd Teorica Real",
    "Corte de Gota %",
    "Objetivo %",
    "Qtd Objetivo",
    "Empacotado %",
    "Qtd Empacotado",
    "Qtd Rejeicao",
    "Rejeição %",
]

for coluna in colunas_float:
    df[coluna] = pd.to_numeric(
        df[coluna]
        .astype("string")
        .str.strip()
        .str.replace("%", "", regex=False)
        .str.replace(",", ".", regex=False),
        errors="coerce",
    )

In [51]:
df

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,7,12,16,960,1,0.6,576.0,0.55,528,0,0.0
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,8,12,16,960,1,0.6,576.0,0.475,456,0,0.0
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,9,12,16,960,1,0.6,576.0,0.5,480,0,0.0
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,10,12,16,960,1,0.6,576.0,0.6,576,0,0.0
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,11,12,16,960,1,0.6,576.0,0.6,576,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,2,90,82,4920,1,0.65,3198.0,0.754472,3712,0,0.0
404,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,3,90,82,4920,1,0.65,3198.0,0.728455,3584,0,0.0
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,4,90,82,4920,1,0.65,3198.0,0.813008,4000,0,0.0
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,5,90,82,4920,1,0.65,3198.0,0.773984,3808,0,0.0
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,6,90,82,4920,1,0.65,3198.0,0.83252,4096,0,0.0

# Desempenho Hora a Hora

In [92]:
tabela = df[
    ["Maquina", "Hora Hora Wht (6to6)", "Objetivo %", "Empacotado %"]
].copy()

tabela["Desempenho Hora"] = (
    tabela["Empacotado %"] - tabela["Objetivo %"]
)

tabela

    Maquina  Hora Hora Wht (6to6)  Objetivo %  Empacotado %  Desempenho Hora
0        10                     7         0.6          0.55            -0.05
1        10                     8         0.6         0.475           -0.125
2        10                     9         0.6           0.5             -0.1
3        10                    10         0.6           0.6              0.0
4        10                    11         0.6           0.6              0.0
..      ...                   ...         ...           ...              ...
403      B7                     2        0.65      0.754472         0.104472
404      B7                     3        0.65      0.728455         0.078455
405      B7                     4        0.65      0.813008         0.163008
406      B7                     5        0.65      0.773984         0.123984
407      B7                     6        0.65       0.83252          0.18252

[408 rows x 5 columns]

# Desempenho Diário

- Objetivo mesmo para todos
- Média empacotado por dia


Desemepenho Diário = Objetivo % - Média Diária por Máquina do Empacotado