# Importando bibliotecas

In [34]:
import pandas as pd

# Importando dados

In [35]:
df_metricas = pd.read_excel('../data/raw/Relatório de Produção - Completo - Dados.xlsx')
df_bloco_notas = pd.read_excel('../data/raw/Relatório de Produção - Completo - Bloco de Notas.xlsx')

c:\Users\evosystem03.ti\Documents\Demanda Carteira\Projeto\predicao-carteira-wheaton\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

# Visualizando dados

In [36]:
display(df_metricas)
display(df_bloco_notas)

,Eficiência Geral,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,7,12,16,960,1,0.6,576,0.55,528,0,0
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,8,12,16,960,1,0.6,576,0.475,456,0,0
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB -1398-S,198594,A,60,9,12,16,960,1,0.6,576,0.5,480,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,2,90,82,4920,1,0.65,3198,0.754472,3712,0,0
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,3,90,82,4920,1,0.65,3198,0.728455,3584,0,0
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,4,90,82,4920,1,0.65,3198,0.813008,4000,0,0
408,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,5,90,82,4920,1,0.65,3198,0.773984,3808,0,0
409,2026-08-10 00:00:00,FORNO B FLINT,B7,MB -1585-S,198546,C,65,6,90,82,4920,1,0.65,3198,0.83252,4096,0,0

,Bloco de Notas - Geral,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Turno Wht,NaN,Maquina,Hora,Funcao,Autor,Nota,Prefixo
2,Manhã,NaN,A1,2026-08-10 06:05:07,Operador AQ,AQA1 Erik Kleiton,"Ferramentas, Equipamentos, Calibres, Rejeitore...",SB -1035-SWN
3,Manhã,NaN,A1,2026-08-10 06:25:17,Esc. Automatica,VINICIUS,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RGA,R...",SB -1035-SWN
4,Manhã,NaN,A1,2026-08-10 08:03:34,Lider AF,Lima,"Ás 08hrs 2 PCTS sem apontar.(2,75%)",SB -1035-SWN
...,...,...,...,...,...,...,...,...
282,Noite,NaN,A5,2026-08-10 04:45:38,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A5 VEL: 242\nDRT: 10029...,SB -1290-S
283,Noite,NaN,A5,2026-08-10 22:07:13,Operador AQ,AQA5 DANILO BATISTA,QUADRO OK\nCALIBRES OK,SB -1290-S
284,Noite,NaN,A5,2026-08-10 22:08:15,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RRS,R...",SB -1290-S
285,Noite,NaN,A6,2026-08-10 04:43:53,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A6 VEL: 170\nDRT: 9363\...,SB -1579-N1N
286,Noite,NaN,A6,2026-08-10 22:08:29,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL2:RFU\nGL3:...",SB -1579-N1N

# Tratando dados

In [37]:
df_metricas.columns = df_metricas.iloc[1]
df_metricas = df_metricas.iloc[2:].reset_index(drop=True)
df_metricas.columns.name = None

colunas_float = [
    "Eficiencia Plan",
    "Hora Hora Wht (6to6)",
    "Veloc Stand",
    "Veloc Real",
    "Qtd Teorica Real",
    "Corte de Gota %",
    "Objetivo %",
    "Qtd Objetivo",
    "Empacotado %",
    "Qtd Empacotado",
    "Qtd Rejeicao",
    "Rejeição %",
]

for coluna in colunas_float:
    df_metricas[coluna] = pd.to_numeric(
        df_metricas[coluna]
        .astype("string")
        .str.strip()
        .str.replace("%", "", regex=False)
        .str.replace(",", ".", regex=False),
        errors="coerce",
    )

# criando variavel de data e hora para juncao com blocos de notas
df_metricas["Data"] = (
    pd.to_datetime(
        df_metricas["Data Wht (dia)"],
        format="%d/%m/%Y",
        errors="coerce"
    )
    + pd.to_timedelta(
        df_metricas["Hora Hora Wht (6to6)"],
        unit="h"
    )
)

df_metricas['Prefixo'] = df_metricas['Prefixo'].str.replace(' ', '').copy()

display(df_metricas)

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %,Data
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,7,12,16,960,1,0.6,576.0,0.55,528,0,0.0,2026-08-10 07:00:00
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,8,12,16,960,1,0.6,576.0,0.475,456,0,0.0,2026-08-10 08:00:00
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,9,12,16,960,1,0.6,576.0,0.5,480,0,0.0,2026-08-10 09:00:00
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,10,12,16,960,1,0.6,576.0,0.6,576,0,0.0,2026-08-10 10:00:00
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,11,12,16,960,1,0.6,576.0,0.6,576,0,0.0,2026-08-10 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,2,90,82,4920,1,0.65,3198.0,0.754472,3712,0,0.0,2026-08-10 02:00:00
404,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,3,90,82,4920,1,0.65,3198.0,0.728455,3584,0,0.0,2026-08-10 03:00:00
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,4,90,82,4920,1,0.65,3198.0,0.813008,4000,0,0.0,2026-08-10 04:00:00
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,5,90,82,4920,1,0.65,3198.0,0.773984,3808,0,0.0,2026-08-10 05:00:00
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,6,90,82,4920,1,0.65,3198.0,0.83252,4096,0,0.0,2026-08-10 06:00:00

In [38]:
# tratamentos df_bloco_notas
display(df_bloco_notas.info())

df_bloco_notas = df_bloco_notas.drop(columns=['Unnamed: 1'])

df_bloco_notas.columns = df_bloco_notas.iloc[1]
df_bloco_notas = df_bloco_notas.iloc[2:].reset_index(drop=True)
df_bloco_notas.columns.name = None

df_bloco_notas['Prefixo'] = df_bloco_notas['Prefixo'].str.replace(' ', '').copy()

df_bloco_notas.rename(columns={'Hora': 'Data'}, inplace=True)

display(df_bloco_notas)

<class 'pandas.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bloco de Notas - Geral  286 non-null    str
 1   Unnamed: 1              0 non-null      float64
 2   Unnamed: 2              286 non-null    str
 3   Unnamed: 3              286 non-null    object
 4   Unnamed: 4              286 non-null    str
 5   Unnamed: 5              286 non-null    str
 6   Unnamed: 6              286 non-null    str
 7   Unnamed: 7              286 non-null    str
dtypes: float64(1), object(1), str(6)
memory usage: 58.5+ KB

None

,Turno Wht,Maquina,Data,Funcao,Autor,Nota,Prefixo
0,Manhã,A1,2026-08-10 06:05:07,Operador AQ,AQA1 Erik Kleiton,"Ferramentas, Equipamentos, Calibres, Rejeitore...",SB-1035-SWN
1,Manhã,A1,2026-08-10 06:25:17,Esc. Automatica,VINICIUS,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RGA,R...",SB-1035-SWN
2,Manhã,A1,2026-08-10 08:03:34,Lider AF,Lima,"Ás 08hrs 2 PCTS sem apontar.(2,75%)",SB-1035-SWN
3,Manhã,A1,2026-08-10 08:43:23,Lider AF,Lima,"Amostra MCAL4 10 frascos (BOA,RCO,DOB) 5,6%",SB-1035-SWN
4,Manhã,A1,2026-08-10 13:17:00,Operador AQ,Dantas 2565,Das 12:04 as 12:10 seção 3 parada devido a ent...,SB-1035-SWN
...,...,...,...,...,...,...,...
280,Noite,A5,2026-08-10 04:45:38,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A5 VEL: 242\nDRT: 10029...,SB-1290-S
281,Noite,A5,2026-08-10 22:07:13,Operador AQ,AQA5 DANILO BATISTA,QUADRO OK\nCALIBRES OK,SB-1290-S
282,Noite,A5,2026-08-10 22:08:15,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RRS,R...",SB-1290-S
283,Noite,A6,2026-08-10 04:43:53,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A6 VEL: 170\nDRT: 9363\...,SB-1579-N1N
284,Noite,A6,2026-08-10 22:08:29,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL2:RFU\nGL3:...",SB-1579-N1N

# Juntando dados

## Anotacoes

Para juntar dados, precisamos da hora exata em que a maquina ficou abaixo do objetivo. 

Olhando os dados que recebemos sobre metricas, nao temos a hora exata, apenas dd/mm/yyyy

Logo, a juncao sera considerando as notas de todo o dia

Variaveis Chaves: Maquina, Prefixo, Data (dd/mm/yyyy hh:mm:ss)

In [39]:
df_metricas

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,Qtd Teorica Real,Corte de Gota %,Objetivo %,Qtd Objetivo,Empacotado %,Qtd Empacotado,Qtd Rejeicao,Rejeição %,Data
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,7,12,16,960,1,0.6,576.0,0.55,528,0,0.0,2026-08-10 07:00:00
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,8,12,16,960,1,0.6,576.0,0.475,456,0,0.0,2026-08-10 08:00:00
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,9,12,16,960,1,0.6,576.0,0.5,480,0,0.0,2026-08-10 09:00:00
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,10,12,16,960,1,0.6,576.0,0.6,576,0,0.0,2026-08-10 10:00:00
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,11,12,16,960,1,0.6,576.0,0.6,576,0,0.0,2026-08-10 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,2,90,82,4920,1,0.65,3198.0,0.754472,3712,0,0.0,2026-08-10 02:00:00
404,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,3,90,82,4920,1,0.65,3198.0,0.728455,3584,0,0.0,2026-08-10 03:00:00
405,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,4,90,82,4920,1,0.65,3198.0,0.813008,4000,0,0.0,2026-08-10 04:00:00
406,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,5,90,82,4920,1,0.65,3198.0,0.773984,3808,0,0.0,2026-08-10 05:00:00
407,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,6,90,82,4920,1,0.65,3198.0,0.83252,4096,0,0.0,2026-08-10 06:00:00

In [40]:
df_bloco_notas

,Turno Wht,Maquina,Data,Funcao,Autor,Nota,Prefixo
0,Manhã,A1,2026-08-10 06:05:07,Operador AQ,AQA1 Erik Kleiton,"Ferramentas, Equipamentos, Calibres, Rejeitore...",SB-1035-SWN
1,Manhã,A1,2026-08-10 06:25:17,Esc. Automatica,VINICIUS,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RGA,R...",SB-1035-SWN
2,Manhã,A1,2026-08-10 08:03:34,Lider AF,Lima,"Ás 08hrs 2 PCTS sem apontar.(2,75%)",SB-1035-SWN
3,Manhã,A1,2026-08-10 08:43:23,Lider AF,Lima,"Amostra MCAL4 10 frascos (BOA,RCO,DOB) 5,6%",SB-1035-SWN
4,Manhã,A1,2026-08-10 13:17:00,Operador AQ,Dantas 2565,Das 12:04 as 12:10 seção 3 parada devido a ent...,SB-1035-SWN
...,...,...,...,...,...,...,...
280,Noite,A5,2026-08-10 04:45:38,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A5 VEL: 242\nDRT: 10029...,SB-1290-S
281,Noite,A5,2026-08-10 22:07:13,Operador AQ,AQA5 DANILO BATISTA,QUADRO OK\nCALIBRES OK,SB-1290-S
282,Noite,A5,2026-08-10 22:08:15,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL3:RRS,RRS,R...",SB-1290-S
283,Noite,A6,2026-08-10 04:43:53,Lider de turno,FABIO,10/08/2026\n\nMÁQUINA A6 VEL: 170\nDRT: 9363\...,SB-1579-N1N
284,Noite,A6,2026-08-10 22:08:29,Esc. Automatica,PATRICK,"CANAIS MAQ MX4\nGL1:RTE,RAB,RAB\nGL2:RFU\nGL3:...",SB-1579-N1N

In [41]:
# Garante que ambas as colunas sejam datetime
df_metricas["Data"] = pd.to_datetime(
    df_metricas["Data"],
    dayfirst=True,
    errors="coerce"
)

df_bloco_notas["Data"] = pd.to_datetime(
    df_bloco_notas["Data"],
    dayfirst=True,
    errors="coerce"
)

# Cria a chave horária para o merge
df_metricas["Data_merge"] = df_metricas["Data"].dt.floor("h")
df_bloco_notas["Data_merge"] = df_bloco_notas["Data"].dt.floor("h")

# Padroniza as demais chaves
chaves_texto = ["Maquina", "Prefixo"]

for coluna in chaves_texto:
    df_metricas[coluna] = (
        df_metricas[coluna]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    df_bloco_notas[coluna] = (
        df_bloco_notas[coluna]
        .astype("string")
        .str.strip()
        .str.upper()
    )

# Merge: one to many -> uma métrica pode estar associada a várias notas
df_final = df_metricas.merge(
    df_bloco_notas,
    how="left",
    on=["Data_merge", "Maquina", "Prefixo"],
    suffixes=("_metrica", "_nota"),
    validate="one_to_many"
)

In [42]:
display(df_final)

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,...,Qtd Empacotado,Qtd Rejeicao,Rejeição %,Data_metrica,Data_merge,Turno Wht,Data_nota,Funcao,Autor,Nota
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,7,12,16,...,528,0,0.0,2026-08-10 07:00:00,2026-08-10 07:00:00,NaN,NaT,NaN,NaN,NaN
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,8,12,16,...,456,0,0.0,2026-08-10 08:00:00,2026-08-10 08:00:00,Manhã,2026-08-10 08:08:53,Operador AQ,Anderson,"Foi feita a troca do molde 90, após verificar ..."
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,9,12,16,...,480,0,0.0,2026-08-10 09:00:00,2026-08-10 09:00:00,NaN,NaT,NaN,NaN,NaN
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,10,12,16,...,576,0,0.0,2026-08-10 10:00:00,2026-08-10 10:00:00,NaN,NaT,NaN,NaN,NaN
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,11,12,16,...,576,0,0.0,2026-08-10 11:00:00,2026-08-10 11:00:00,Manhã,2026-08-10 11:10:33,Lider AF,OLIVEIRA,10:00 FOI TIRADO DA PRODUÇÃO 7 CXS\n11:00 FOI ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,2,90,82,...,3712,0,0.0,2026-08-10 02:00:00,2026-08-10 02:00:00,NaN,NaT,NaN,NaN,NaN
521,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,3,90,82,...,3584,0,0.0,2026-08-10 03:00:00,2026-08-10 03:00:00,Noite,2026-08-10 03:43:37,Operador AQ,AQB7 GUILHERME DE MACEDO,Foi separado equipamento de molde (C75) e leva...
522,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,4,90,82,...,4000,0,0.0,2026-08-10 04:00:00,2026-08-10 04:00:00,Noite,2026-08-10 04:45:07,Operador AQ,AQB7 GUILHERME DE MACEDO,Final de turno\n\n- Calibres ok \n- Ferramenta...
523,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,5,90,82,...,3808,0,0.0,2026-08-10 05:00:00,2026-08-10 05:00:00,NaN,NaT,NaN,NaN,NaN
524,2026-08-10 00:00:00,FORNO B FLINT,B7,MB-1585-S,198546,C,65,6,90,82,...,4096,0,0.0,2026-08-10 06:00:00,2026-08-10 06:00:00,NaN,NaT,NaN,NaN,NaN

In [44]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data Wht (dia)        525 non-null    object
 1   Forno                 525 non-null    str
 2   Maquina               525 non-null    string
 3   Prefixo               525 non-null    string
 4   OP Vertech            525 non-null    str
 5   NQI                   525 non-null    str
 6   Eficiencia Plan       525 non-null    Int64
 7   Hora Hora Wht (6to6)  525 non-null    Int64
 8   Veloc Stand           525 non-null    Int64
 9   Veloc Real            525 non-null    Int64
 10  Qtd Teorica Real      525 non-null    Int64
 11  Corte de Gota %       525 non-null    Int64
 12  Objetivo %            525 non-null    Float64
 13  Qtd Objetivo          525 non-null    Float64
 14  Empacotado %          525 non-null    Float64
 15  Qtd Empacotado        525 non-null    Int64
 16  Qtd Rejeicao          525 non-null    Int64
 17  Rejeição %            525 non-null    Float64
 18  Data_metrica          525 non-null    datetime64[us]
 19  Data_merge            525 non-null    datetime64[us]
 20  Turno Wht             275 non-null    str
 21  Data_nota             275 non-null    datetime64[us]
 22  Funcao                275 non-null    str
 23  Autor                 275 non-null    str
 24  Nota                  275 non-null    str
dtypes: Float64(4), Int64(8), datetime64[us](3), object(1), str(7), string(2)
memory usage: 161.3+ KB

In [ ]:
# filtrando uma maquina para verificar resultados

# OBS: esta maquina so tem registros para producao de um prefixo, logo nao precisei filtrar por prefixo!!!
# Em casos de outras maquinas, para puxar as notas corretamente, deveria filtrar especificamente uma maquina e um prefixo que ela produziu

maq_10 = df_final.loc[df_final['Maquina'] == '10'].copy()
display(maq_10)

# Aparentemente, as notas estao juntas corretamente com os dados de metricas das maquinas

,Data Wht (dia),Forno,Maquina,Prefixo,OP Vertech,NQI,Eficiencia Plan,Hora Hora Wht (6to6),Veloc Stand,Veloc Real,...,Qtd Empacotado,Qtd Rejeicao,Rejeição %,Data_metrica,Data_merge,Turno Wht,Data_nota,Funcao,Autor,Nota
0,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,7,12,16,...,528,0,0.0,2026-08-10 07:00:00,2026-08-10 07:00:00,NaN,NaT,NaN,NaN,NaN
1,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,8,12,16,...,456,0,0.0,2026-08-10 08:00:00,2026-08-10 08:00:00,Manhã,2026-08-10 08:08:53,Operador AQ,Anderson,"Foi feita a troca do molde 90, após verificar ..."
2,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,9,12,16,...,480,0,0.0,2026-08-10 09:00:00,2026-08-10 09:00:00,NaN,NaT,NaN,NaN,NaN
3,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,10,12,16,...,576,0,0.0,2026-08-10 10:00:00,2026-08-10 10:00:00,NaN,NaT,NaN,NaN,NaN
4,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,11,12,16,...,576,0,0.0,2026-08-10 11:00:00,2026-08-10 11:00:00,Manhã,2026-08-10 11:10:33,Lider AF,OLIVEIRA,10:00 FOI TIRADO DA PRODUÇÃO 7 CXS\n11:00 FOI ...
5,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,11,12,16,...,576,0,0.0,2026-08-10 11:00:00,2026-08-10 11:00:00,Manhã,2026-08-10 11:12:54,Lider AF,OLIVEIRA,35.00%
6,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,12,12,16,...,576,0,0.0,2026-08-10 12:00:00,2026-08-10 12:00:00,Manhã,2026-08-10 12:08:56,Lider AF,OLIVEIRA,12:00 foi tirado 6 cxs para completar revisão ...
7,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,12,12,16,...,576,0,0.0,2026-08-10 12:00:00,2026-08-10 12:00:00,Manhã,2026-08-10 12:12:59,Operador AQ,Anderson,"Foi feita a troca das 2 pinças, mesa 1 estava ..."
8,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,13,12,16,...,600,0,0.0,2026-08-10 13:00:00,2026-08-10 13:00:00,Manhã,2026-08-10 13:15:44,Lider AF,OLIVEIRA,13:00 FOI TIRADO DA PRODUÇÃO 5 CXS PARA COMPLE...
9,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,13,12,16,...,600,0,0.0,2026-08-10 13:00:00,2026-08-10 13:00:00,Manhã,2026-08-10 13:27:58,Operador AQ,Anderson,durante o turno tivemos o problema persistente...
10,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,13,12,16,...,600,0,0.0,2026-08-10 13:00:00,2026-08-10 13:00:00,Manhã,2026-08-10 13:32:55,Lider de turno,Jatobá,OBS:\nDurante o turno tivemos problemas com LA...
11,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,14,12,16,...,600,0,0.0,2026-08-10 14:00:00,2026-08-10 14:00:00,NaN,NaT,NaN,NaN,NaN
12,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,15,12,16,...,456,0,0.0,2026-08-10 15:00:00,2026-08-10 15:00:00,NaN,NaT,NaN,NaN,NaN
13,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,16,12,16,...,528,2880,3.0,2026-08-10 16:00:00,2026-08-10 16:00:00,NaN,NaT,NaN,NaN,NaN
14,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,17,12,16,...,624,0,0.0,2026-08-10 17:00:00,2026-08-10 17:00:00,NaN,NaT,NaN,NaN,NaN
15,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,18,12,16,...,552,0,0.0,2026-08-10 18:00:00,2026-08-10 18:00:00,NaN,NaT,NaN,NaN,NaN
16,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,19,12,16,...,600,0,0.0,2026-08-10 19:00:00,2026-08-10 19:00:00,NaN,NaT,NaN,NaN,NaN
17,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,20,12,16,...,648,0,0.0,2026-08-10 20:00:00,2026-08-10 20:00:00,Tarde,2026-08-10 20:37:55,Lider AF,LILIAN,Feito amostra do CACO com 15 frascos todos rui...
18,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,21,12,16,...,600,2880,3.0,2026-08-10 21:00:00,2026-08-10 21:00:00,NaN,NaT,NaN,NaN,NaN
19,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,22,12,16,...,288,0,0.0,2026-08-10 22:00:00,2026-08-10 22:00:00,Noite,2026-08-10 22:47:51,Lider AF,PAMELY 10,N11 J.F DAS 22:11H AS 22:45HRS
20,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,23,12,16,...,360,0,0.0,2026-08-10 23:00:00,2026-08-10 23:00:00,NaN,NaT,NaN,NaN,NaN
21,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,0,12,16,...,696,0,0.0,2026-08-10 00:00:00,2026-08-10 00:00:00,NaN,NaT,NaN,NaN,NaN
22,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,1,12,16,...,504,0,0.0,2026-08-10 01:00:00,2026-08-10 01:00:00,Noite,2026-08-10 01:21:23,Operador AQ,AQD10 Isac Rocha,01:07 as 01:10 desvio para acerto de peso.
23,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,2,12,16,...,576,0,0.0,2026-08-10 02:00:00,2026-08-10 02:00:00,NaN,NaT,NaN,NaN,NaN
24,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,3,12,16,...,648,0,0.0,2026-08-10 03:00:00,2026-08-10 03:00:00,NaN,NaT,NaN,NaN,NaN
25,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,4,12,16,...,648,0,0.0,2026-08-10 04:00:00,2026-08-10 04:00:00,NaN,NaT,NaN,NaN,NaN
26,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,5,12,16,...,672,0,0.0,2026-08-10 05:00:00,2026-08-10 05:00:00,Noite,2026-08-10 05:31:29,Operador AQ,AQD10 Isac Rocha,Obs: No inicio do turno tivemos problemas com...
27,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,5,12,16,...,672,0,0.0,2026-08-10 05:00:00,2026-08-10 05:00:00,Noite,2026-08-10 05:35:41,Operador AQ,AQD10 Isac Rocha,obs:Varão do peso sensível (atenção)
28,2026-08-10 00:00:00,FORNO 1 FLINT,10,MB-1398-S,198594,A,60,6,12,16,...,792,0,0.0,2026-08-10 06:00:00,2026-08-10 06:00:00,NaN,NaT,NaN,NaN,NaN