# Anotacoes

**Pontos a entender:**

- Como classificar os desvios de producao com maiores perdas?
    - Digo isso pois nem sempre aquele desvio mais frequente causou mais perdas

# Importando bibliotecas

In [45]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Importando dados

In [46]:
df = pd.read_excel('../data/raw/Amostragem AF Frascos.xlsx')

# Visualizando dados

In [47]:
df

,Bom / Ruim,Compatível,Fábrica,Fabrica – Linha,Linha,Ordem de trabalhos,Ref. do artigo,Artigo,Fase de controle,Tipo de controle,...,Data de medição,Chave primária,Dia da amostra,Dia de medição,Controle/Tipo de fase,Mudança da amostra,Chave primária de controle,Diferença entre dados de amostragem e de medição,Comentário,Número do lote de produção
0,1,Boa,Wheaton,Wheaton - 11,11,198660,C1418.0000P,LB -0586-S | F | NH | B | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-24 10:15:29,3445332,2026-08-24,2026-08-24,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,356240,0.0000,NaN,1.0
1,1,Boa,Wheaton,Wheaton - A2,A2,198698,F0685.0000V,SB -1036-SWN | A | NH | F | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-24 10:15:19,3445330,2026-08-24,2026-08-24,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,356380,0.0000,NaN,1.0
2,1,Boa,Wheaton,Wheaton - B8,B8,198710,C1181.0000R,LB -0505-SX | F | NH | B | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA VAZIA,...,2026-08-24 10:15:20,3445331,2026-08-24,2026-08-24,26 - VOLUMETRIA CADA 1 HORA - GARRAFA VAZIA,1,357063,0.0081,NaN,1.0
3,1,Boa,Wheaton,Wheaton - B7,B7,198750,C1444.0000R,SB -1726-S | F | NH | C | LISO,25 - DIMENSIONAL CADA 1 HORA,H,...,2026-08-24 10:15:33,3445333,2026-08-24,2026-08-24,25 - DIMENSIONAL CADA 1 HORA - H,1,358638,0.0147,NaN,1.0
4,1,Boa,Wheaton,Wheaton - B5,B5,198665,C0763.0000R,SB -1483-S | F | NH | E | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA VAZIA,...,2026-08-24 10:13:18,3445329,2026-08-24,2026-08-24,26 - VOLUMETRIA CADA 1 HORA - GARRAFA VAZIA,1,357381,0.0119,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190512,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,31 - CALIBRES DE CORPO,MEDIDA CORPO LARGURA,...,2026-08-01 06:24:46,3386270,2026-08-01,2026-08-01,31 - CALIBRES DE CORPO - MEDIDA CORPO LARGURA,1,338310,0.4128,NaN,1.0
190513,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,31 - CALIBRES DE CORPO,MEDIDA CORPO ESPESSURA,...,2026-08-01 06:24:46,3386270,2026-08-01,2026-08-01,31 - CALIBRES DE CORPO - MEDIDA CORPO ESPESSURA,1,338311,0.4128,NaN,1.0
190514,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA NÃO PASSA,...,2026-08-01 06:24:47,3386270,2026-08-01,2026-08-01,31 - CALIBRES DE CORPO - MEDIDA ALTURA NÃO PASSA,1,338312,0.4131,NaN,1.0
190515,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA PASSA,...,2026-08-01 06:24:47,3386270,2026-08-01,2026-08-01,31 - CALIBRES DE CORPO - MEDIDA ALTURA PASSA,1,338313,0.4131,NaN,1.0
190516,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,31 - CALIBRES DE CORPO,VERTICALIDADE (MESA GIRATÓRIA),...,2026-08-01 06:24:47,3386270,2026-08-01,2026-08-01,31 - CALIBRES DE CORPO - VERTICALIDADE (MESA G...,1,338314,0.4131,NaN,1.0

# Tratando dados

In [48]:
# ordenando base por data de "Amostra coletada em"
df = df.sort_values(by='Amostra coletada em', ascending=True).copy()

# Localizando variaveis referentes a datas
display(df[['Amostra coletada em', 'Data de medição', 'Dia da amostra', 'Dia de medição']])

# Filtrando base para pegar apenas dados das datas proximas de 10/08/2026 -> proximas pois preciso validar hora wheaton
df = df.loc[df['Amostra coletada em'] <= "2026-08-11 08:00:00"].copy()
df = df.loc[df['Amostra coletada em'] >= "2026-08-09 06:00:00"].copy()
display(df)

       Amostra coletada em     Data de medição Dia da amostra Dia de medição
190516 2026-08-01 06:00:00 2026-08-01 06:24:47     2026-08-01     2026-08-01
190506 2026-08-01 06:00:00 2026-08-01 06:24:43     2026-08-01     2026-08-01
190507 2026-08-01 06:00:00 2026-08-01 06:24:44     2026-08-01     2026-08-01
190508 2026-08-01 06:00:00 2026-08-01 06:24:44     2026-08-01     2026-08-01
190509 2026-08-01 06:00:00 2026-08-01 06:24:44     2026-08-01     2026-08-01
...                    ...                 ...            ...            ...
4      2026-08-24 10:12:35 2026-08-24 10:13:18     2026-08-24     2026-08-24
3      2026-08-24 10:14:40 2026-08-24 10:15:33     2026-08-24     2026-08-24
2      2026-08-24 10:14:51 2026-08-24 10:15:20     2026-08-24     2026-08-24
1      2026-08-24 10:15:19 2026-08-24 10:15:19     2026-08-24     2026-08-24
0      2026-08-24 10:15:29 2026-08-24 10:15:29     2026-08-24     2026-08-24

[190517 rows x 4 columns]

,Bom / Ruim,Compatível,Fábrica,Fabrica – Linha,Linha,Ordem de trabalhos,Ref. do artigo,Artigo,Fase de controle,Tipo de controle,...,Data de medição,Chave primária,Dia da amostra,Dia de medição,Controle/Tipo de fase,Mudança da amostra,Chave primária de controle,Diferença entre dados de amostragem e de medição,Comentário,Número do lote de produção
127407,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-09 06:00:19,3406116,2026-08-09,2026-08-09,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,338302,0.0006,NaN,1.0
127404,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA VAZIA,...,2026-08-09 06:00:59,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - GARRAFA VAZIA,1,356264,0.0081,NaN,1.0
127406,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,VOLUMETRIA TOTAL,...,2026-08-09 06:03:28,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - VOLUMETRIA TOTAL,1,356266,0.0494,NaN,1.0
127405,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA CHEIA,...,2026-08-09 06:02:39,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - GARRAFA CHEIA,1,356265,0.0358,NaN,1.0
127403,1,Boa,Wheaton,Wheaton - 15,15,198456,C1199.0000P,LB -0491-N1 | F | NH | A | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-09 06:00:32,3406117,2026-08-09,2026-08-09,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,352975,0.0000,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109228,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,29 - CALIBRE TERMINAÇÃO,CALIBRE ANEL PASSA,...,2026-08-11 09:09:31,3411524,2026-08-11,2026-08-11,29 - CALIBRE TERMINAÇÃO - CALIBRE ANEL PASSA,1,356220,1.1586,NaN,1.0
109229,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA NÃO PASSA,...,2026-08-11 09:09:36,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - MEDIDA ALTURA NÃO PASSA,1,356221,1.1600,NaN,1.0
109230,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA PASSA,...,2026-08-11 09:09:41,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - MEDIDA ALTURA PASSA,1,356222,1.1614,NaN,1.0
109231,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,CORPO DIAMETRO,...,2026-08-11 09:09:45,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - CORPO DIAMETRO,1,356223,1.1625,NaN,1.0
109226,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,29 - CALIBRE TERMINAÇÃO,MEDIDA E NÃO PASSA,...,2026-08-11 09:09:20,3411524,2026-08-11,2026-08-11,29 - CALIBRE TERMINAÇÃO - MEDIDA E NÃO PASSA,1,356218,1.1556,NaN,1.0

# Analises

## Localizando producoes em analise

In [49]:
OPs = [
    '198594', '198660', '198592', '198176', '198456', '198618',
    '198698', '198567', '198135', '198659', '198639', '198645',
    '198701', '198704', '198707', '198694', '198658', '198663',
    '198613', '198693', '198546'
]

# Padroniza as ordens como texto
df['Ordem de trabalhos'] = (
    df['Ordem de trabalhos']
    .astype(str)
    .str.strip()
)

# Padroniza os tipos de controle como texto
df['Tipo de controle'] = (
    df['Tipo de controle']
    .astype(str)
    .str.strip()
)

# Filtra somente as ordens desejadas
df = df[
    df['Ordem de trabalhos'].isin(OPs)
].copy()

display(df)

,Bom / Ruim,Compatível,Fábrica,Fabrica – Linha,Linha,Ordem de trabalhos,Ref. do artigo,Artigo,Fase de controle,Tipo de controle,...,Data de medição,Chave primária,Dia da amostra,Dia de medição,Controle/Tipo de fase,Mudança da amostra,Chave primária de controle,Diferença entre dados de amostragem e de medição,Comentário,Número do lote de produção
127407,1,Boa,Wheaton,Wheaton - 14,14,198176,C0091.0000P,LB -0478-N1 | F | FP | A | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-09 06:00:19,3406116,2026-08-09,2026-08-09,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,338302,0.0006,NaN,1.0
127404,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA VAZIA,...,2026-08-09 06:00:59,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - GARRAFA VAZIA,1,356264,0.0081,NaN,1.0
127406,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,VOLUMETRIA TOTAL,...,2026-08-09 06:03:28,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - VOLUMETRIA TOTAL,1,356266,0.0494,NaN,1.0
127405,1,Boa,Wheaton,Wheaton - 12,12,198592,C1429.0000P,MB -1512-SN | F | NH | C | LISO,26 - VOLUMETRIA CADA 1 HORA,GARRAFA CHEIA,...,2026-08-09 06:02:39,3406120,2026-08-09,2026-08-09,26 - VOLUMETRIA CADA 1 HORA - GARRAFA CHEIA,1,356265,0.0358,NaN,1.0
127403,1,Boa,Wheaton,Wheaton - 15,15,198456,C1199.0000P,LB -0491-N1 | F | NH | A | LISO,27 - PESO AREA QUENTE,PESO AREA QUENTE,...,2026-08-09 06:00:32,3406117,2026-08-09,2026-08-09,27 - PESO AREA QUENTE - PESO AREA QUENTE,1,352975,0.0000,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109228,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,29 - CALIBRE TERMINAÇÃO,CALIBRE ANEL PASSA,...,2026-08-11 09:09:31,3411524,2026-08-11,2026-08-11,29 - CALIBRE TERMINAÇÃO - CALIBRE ANEL PASSA,1,356220,1.1586,NaN,1.0
109229,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA NÃO PASSA,...,2026-08-11 09:09:36,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - MEDIDA ALTURA NÃO PASSA,1,356221,1.1600,NaN,1.0
109230,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,MEDIDA ALTURA PASSA,...,2026-08-11 09:09:41,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - MEDIDA ALTURA PASSA,1,356222,1.1614,NaN,1.0
109231,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,31 - CALIBRES DE CORPO,CORPO DIAMETRO,...,2026-08-11 09:09:45,3411524,2026-08-11,2026-08-11,31 - CALIBRES DE CORPO - CORPO DIAMETRO,1,356223,1.1625,NaN,1.0
109226,1,Boa,Wheaton,Wheaton - A4,A4,198659,F0732.0000V,SB -1348-S | A | NH | F | LISO,29 - CALIBRE TERMINAÇÃO,MEDIDA E NÃO PASSA,...,2026-08-11 09:09:20,3411524,2026-08-11,2026-08-11,29 - CALIBRE TERMINAÇÃO - MEDIDA E NÃO PASSA,1,356218,1.1556,NaN,1.0

## Maiores desvios por producao

In [50]:
# Conta cada Tipo de controle por Ordem de trabalhos
contagem = (
    df
    .groupby(['Ordem de trabalhos', 'Tipo de controle'])
    .size()
    .reset_index(name='Quantidade')
)

# Ordena para destacar os tipos mais presentes
contagem = contagem.sort_values(
    ['Ordem de trabalhos', 'Quantidade'],
    ascending=[True, False]
)

# Gráfico com os eixos invertidos
fig = px.bar(
    contagem,
    x='Quantidade',
    y='Ordem de trabalhos',
    color='Tipo de controle',
    orientation='h',
    barmode='group',
    text='Tipo de controle',
    title='Desvios mais frequentes por OP',
    labels={
        'Ordem de trabalhos': 'Ordem de trabalho',
        'Quantidade': 'Número de ocorrências'
    }
)

# Guarda os nomes, cores e dados originais do gráfico
nomes_originais = [
    trace.name
    for trace in fig.data
]

cores_tipos = {
    trace.name: trace.marker.color
    for trace in fig.data
}

dados_originais = {
    'x': [
        list(trace.x)
        for trace in fig.data
    ],
    'y': [
        list(trace.y)
        for trace in fig.data
    ],
    'text': [
        list(trace.text)
        for trace in fig.data
    ],
    'name': nomes_originais,
    'marker.color': [
        trace.marker.color
        for trace in fig.data
    ],
    'visible': [True] * len(fig.data)
}


# Retorna os dados de uma ordem específica
def filtrar_grafico(op=None):

    # Retorna todas as ordens
    if op is None:
        return dados_originais

    # A ordem crescente é intencional:
    # no gráfico horizontal, o último trace aparece no topo
    dados = (
        contagem[
            contagem['Ordem de trabalhos'] == op
        ]
        .sort_values(
            ['Quantidade', 'Tipo de controle'],
            ascending=[True, False]
        )
        .reset_index(drop=True)
    )

    valores_x = []
    valores_y = []
    valores_texto = []
    nomes = []
    cores = []
    visibilidade = []

    for posicao in range(len(fig.data)):

        if posicao < len(dados):
            linha = dados.iloc[posicao]

            tipo = str(linha['Tipo de controle'])
            quantidade = linha['Quantidade']

            valores_x.append([quantidade])
            valores_y.append([op])
            valores_texto.append([quantidade])

            nomes.append(tipo)
            cores.append(cores_tipos[tipo])
            visibilidade.append(True)

        else:
            # Oculta os traces que não são utilizados pela ordem
            nome_original = nomes_originais[posicao]

            valores_x.append([])
            valores_y.append([])
            valores_texto.append([])

            nomes.append(nome_original)
            cores.append(cores_tipos[nome_original])
            visibilidade.append(False)

    return {
        'x': valores_x,
        'y': valores_y,
        'text': valores_texto,
        'name': nomes,
        'marker.color': cores,
        'visible': visibilidade
    }


# Opção para visualizar todas as ordens
botoes = [
    dict(
        label='Todas',
        method='update',
        args=[
            filtrar_grafico(),
            {
                'title': 'Desvios mais frequentes por OP'
            }
        ]
    )
]

# Adiciona cada ordem ao dropdown
for op in OPs:
    botoes.append(
        dict(
            label=op,
            method='update',
            args=[
                filtrar_grafico(op),
                {
                    'title': f'Desvios mais frequentes da OP {op}'
                }
            ]
        )
    )

fig.update_layout(
    updatemenus=[
        dict(
            buttons=botoes,
            direction='down',
            x=0,
            y=1.15,
            showactive=True
        )
    ],
    yaxis={
        'type': 'category',
        'categoryorder': 'array',
        'categoryarray': OPs[::-1]
    },
    legend_title_text='Tipo de controle',
    legend_traceorder='reversed',
    hovermode='y unified'
)

fig.update_traces(
    textposition='outside',
    cliponaxis=False
)

fig.show()