# Anotacoes

Perdas com valores positivos
- Anteriormente em primeira coleta de dados, foram encontrados perdas com valores positivos
- Rapha forneceu nova coleta, informando que:
    - "Só um ponto, precisa desconsiderar as Perdas EM (que seriam as escolhas manuais) do Forno A"
- Farei analise diante dados do Forno A para corrigir esse calculo, assim validar com Raphael

<br>

Perguntas:
- Se somar "Perdas EA" + "Perdas EM" da o valor de "Perdas Total AF"?
    - Sim, Perdas total AF depende dos valores das perdas EA e perdas EM
    - Logo tambem esta incorreta

- Se desconsiderar "Perdas EM" conforme Rapha orientou pois estao com valores positivos, resolve o problema?
    - Nao, pois Perdas total AF considera a soma de Perdas EA e Perdas EM

- Ha outras entradas que podem estar sendo calculadas erradas?
    - Sim, ha as seguintes OPs que possuem perdas com sinal positivo que impactam no valor de cada entrada
        - OP 198639 -> Perdas Recozimento (54)
        - OP 198645 -> Perdas Maq-Rec (2346) e Perdas Recozimento (319)
        - OP 198693 -> Perdas Recozimento (11513) e Perdas EM (34392)
        - OP 198663 -> Perdas Maq-Rec (562) e Perdas EM (7382)
        - OP 198613 -> Perdas Maq-Rec (7362)

            | Entrada validada | IGUAL | DIFERENTE | OPs divergentes |
            | --- | --- | --- | --- | 
            | Qtd Entrada Recoz. | 18 | 3 | 198613, 198645, 198663 |
            | Qtd Entrada AF | 18 | 3 | 198639, 198645, 198693 |
            | Perdas total AF | 16 | 5 | 198135, 198659, 198663, 198698, 198707 |
            | Qtd Empacotado | 15 | 6 | 198135, 198659, 198663, 198693, 198698, 198707 |

    - Preciso corrigir o sinal dessas perdas e corrigir o valor calculado das entradas

- Corrigir o calculo das zonas de entradas aumentou a quantidade de OPs com empacotado igual entre as bases?
    - Nao, se manteve em 6 OPs com valores iguais e 15 diferentes
    - Isso prova que ha um problema nao so de sinais, mas sim de valores das producoes
    - Interessante analisar os valores de Qtd Gotas Cortadas de cada OP entre as bases

- Valores de "Qtd Gotas Cortadas" por OP entre as duas bases sao iguais? Precisam ser...

# Importando bibliotecas

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

import plotly.express as px
import plotly.graph_objects as go

import ipywidgets as widgets
from IPython.display import display, Markdown

from plotly.subplots import make_subplots

# Importando dados

In [2]:
df = pd.read_excel('../data/raw/Zonas e Perdas (sensor) acumulado dia.xlsx')
df_desemp_emp_diario = pd.read_excel('../data/processed/desempenho_empacotamento_diario.xlsx')

# Visualizando dados

In [3]:
df

,Acumulado Dia,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
2,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Gotas cortadas,1
3,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Entrada Recozi.,0.957291
4,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Entrada AF,0.938881
...,...,...,...,...,...,...,...
501,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Maq-Rec,-526
502,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Recozimento,-3599
503,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EM,-5319
504,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EA,-951
505,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas total AF,-6270

# Tratando dados

In [4]:
# Define a linha de índice 1 como cabeçalho
df.columns = df.iloc[1]

# Remove as linhas anteriores ao início dos dados
df = df.iloc[2:].reset_index(drop=True)

display(df)

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
0,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Gotas cortadas,1
1,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Entrada Recozi.,0.957291
2,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Entrada AF,0.938881
3,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Empacotado,0.890145
4,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,%Perdas parada seção,-0.006657
...,...,...,...,...,...,...,...
499,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Maq-Rec,-526
500,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Recozimento,-3599
501,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EM,-5319
502,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EA,-951
503,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas total AF,-6270

In [5]:
# visualizando variaveis e seus tipos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data Wheaton (dia)  504 non-null    object
 1   Forno               504 non-null    str
 2   Maquina             504 non-null    str
 3   Prefixo             504 non-null    str
 4   Ordem Producao      504 non-null    str
 5   Entradas / Perdas   504 non-null    str
 6   Qtd Frascos         504 non-null    object
dtypes: object(2), str(5)
memory usage: 45.9+ KB

In [6]:
# verificando valores unicos de Entradas / Perdas
display(df['Entradas / Perdas'].value_counts())

# filtrando apenas Entradas / Perdas em quantidade (descartando as percentuais)
df = df[~df['Entradas / Perdas'].str.startswith('%', na=False)].copy()
display(df['Entradas / Perdas'].value_counts())

Entradas / Perdas
%Gotas cortadas           21
%Entrada Recozi.          21
%Entrada AF               21
%Empacotado               21
%Perdas parada seção      21
%Perdas seções rejeito    21
%Perdas Maq-Rec           21
%Perdas Total AQ          21
%Perdas Recozimento       21
%Perdas EA                21
%Perdas EM                21
%Perdas Total AF          21
Qtd Gotas Cortadas        21
Qtd Entrada Recoz.        21
Qtd Entrada AF            21
Qtd Empacotado            21
Paradas de seção          21
Perdas seções rejeito     21
Perdas Total AQ           21
Perdas Maq-Rec            21
Perdas Recozimento        21
Perdas EM                 21
Perdas EA                 21
Perdas total AF           21
Name: count, dtype: int64

Entradas / Perdas
Qtd Gotas Cortadas       21
Qtd Entrada Recoz.       21
Qtd Entrada AF           21
Qtd Empacotado           21
Paradas de seção         21
Perdas seções rejeito    21
Perdas Total AQ          21
Perdas Maq-Rec           21
Perdas Recozimento       21
Perdas EM                21
Perdas EA                21
Perdas total AF          21
Name: count, dtype: int64

In [7]:
# tratando perdas com valores positivos - devem ser negativos
df_perdas_tratadas = df.copy()

'''# entradas sao pontos de medicao, nao perdas: precisam continuar positivas
entradas = [
    'Qtd Gotas Cortadas',
    'Qtd Entrada Recoz.',
    'Qtd Entrada AF',
    'Qtd Empacotado',
]

# o df original fica intacto, o tratamento vai para um df novo
df_perdas_tratadas = df.copy()

# tudo que nao e entrada e perda: se estiver positivo, passa a negativo
perdas_positivas = (
    (~df_perdas_tratadas['Entradas / Perdas'].isin(entradas))
    &
    (df_perdas_tratadas['Qtd Frascos'] > 0)
)
df_perdas_tratadas.loc[perdas_positivas, 'Qtd Frascos'] = (
    -df_perdas_tratadas.loc[perdas_positivas, 'Qtd Frascos']
)

print(f'{perdas_positivas.sum()} perda(s) positiva(s) convertida(s) para negativo')'''

"# entradas sao pontos de medicao, nao perdas: precisam continuar positivas\nentradas = [\n    'Qtd Gotas Cortadas',\n    'Qtd Entrada Recoz.',\n    'Qtd Entrada AF',\n    'Qtd Empacotado',\n]\n\n# o df original fica intacto, o tratamento vai para um df novo\ndf_perdas_tratadas = df.copy()\n\n# tudo que nao e entrada e perda: se estiver positivo, passa a negativo\nperdas_positivas = (\n    (~df_perdas_tratadas['Entradas / Perdas'].isin(entradas))\n    &\n    (df_perdas_tratadas['Qtd Frascos'] > 0)\n)\ndf_perdas_tratadas.loc[perdas_positivas, 'Qtd Frascos'] = (\n    -df_perdas_tratadas.loc[perdas_positivas, 'Qtd Frascos']\n)\n\nprint(f'{perdas_positivas.sum()} perda(s) positiva(s) convertida(s) para negativo')"

# Analises (df_perdas_tratadas)

## Validando calculo da entrada "Qtd Entrada Recoz"

In [8]:
# essa analise consiste em validar se a Qtd Entrada Recoz. realmente esta correta
# Qtd Entrada Recoz. = Qtd Gotas Cortadas + (Paradas de seção + Perdas seções rejeito + Perdas Maq-Rec)

# uma linha por OP com as zonas que entram nesse calculo
entrada_recoz = df_perdas_tratadas[
    df_perdas_tratadas['Entradas / Perdas'].isin([
        'Qtd Gotas Cortadas',
        'Paradas de seção',
        'Perdas seções rejeito',
        'Perdas Maq-Rec',
        'Qtd Entrada Recoz.',
    ])
].pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# refazendo a conta para comparar com o valor que veio na base
entrada_recoz['Entrada Recoz. calculada'] = (
    entrada_recoz['Qtd Gotas Cortadas']
    + entrada_recoz['Paradas de seção']
    + entrada_recoz['Perdas seções rejeito']
    + entrada_recoz['Perdas Maq-Rec']
)
entrada_recoz['Diferença'] = (
    entrada_recoz['Qtd Entrada Recoz.'] - entrada_recoz['Entrada Recoz. calculada']
)

entrada_recoz['Situação'] = 'DIFERENTE'
entrada_recoz.loc[entrada_recoz['Diferença'] == 0, 'Situação'] = 'IGUAL'

qtd_iguais = int((entrada_recoz['Situação'] == 'IGUAL').sum())
qtd_diferentes = int((entrada_recoz['Situação'] == 'DIFERENTE').sum())

display(Markdown(f'### {qtd_iguais} igual(is) e {qtd_diferentes} diferente(s) de {len(entrada_recoz)} OPs'))
display(entrada_recoz)

### 21 igual(is) e 0 diferente(s) de 21 OPs

Entradas / Perdas,Paradas de seção,Perdas Maq-Rec,Perdas seções rejeito,Qtd Entrada Recoz.,Qtd Gotas Cortadas,Entrada Recoz. calculada,Diferença,Situação
Ordem Producao,,,,,,,,
198135,-1708,-2236,-4260,205026,213230,205026,0,IGUAL
198176,-4032,-312,0,12928,17272,12928,0,IGUAL
198456,-8297,-1226,-2171,32957,44651,32957,0,IGUAL
198546,-1244,-5444,-3587,107915,118190,107915,0,IGUAL
198567,-586,-57,-474,17121,18238,17121,0,IGUAL
198592,-546,-4382,-3208,66712,74848,66712,0,IGUAL
198594,-38,-666,-532,21803,23039,21803,0,IGUAL
198613,-77613,7364,-5089,260413,335751,260413,0,IGUAL
198618,-1152,-4945,-1294,165664,173055,165664,0,IGUAL
198639,-1904,-6832,-1093,338219,348048,338219,0,IGUAL
198645,-2346,2346,-8864,235504,244368,235504,0,IGUAL
198658,-233,-2030,-2293,41523,46079,41523,0,IGUAL
198659,-1221,-4660,-4310,292224,302415,292224,0,IGUAL
198660,-1014,-526,-2086,33941,37567,33941,0,IGUAL
198663,-891,562,-91,6630,7050,6630,0,IGUAL
198693,-17592,-722,0,24873,43187,24873,0,IGUAL
198694,-2648,-5139,-8403,173904,190094,173904,0,IGUAL
198698,-10738,-32963,-7826,72485,124012,72485,0,IGUAL
198701,-34,-1301,0,7410,8745,7410,0,IGUAL
198704,-445,-2563,0,24713,27721,24713,0,IGUAL
198707,-21,-1346,0,9687,11054,9687,0,IGUAL

## Validando calculo da entrada "Qtd Entrada AF"

In [9]:
# essa analise consiste em validar se a Qtd Entrada AF realmente esta correta
# Qtd Entrada AF = Qtd Entrada Recoz. + Perdas Recozimento

# uma linha por OP com as zonas que entram nesse calculo
entrada_af = df_perdas_tratadas[
    df_perdas_tratadas['Entradas / Perdas'].isin([
        'Qtd Entrada Recoz.',
        'Perdas Recozimento',
        'Qtd Entrada AF',
    ])
].pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# refazendo a conta para comparar com o valor que veio na base
entrada_af['Entrada AF calculada'] = (
    entrada_af['Qtd Entrada Recoz.'] + entrada_af['Perdas Recozimento']
)
entrada_af['Diferença'] = entrada_af['Qtd Entrada AF'] - entrada_af['Entrada AF calculada']

entrada_af['Situação'] = 'DIFERENTE'
entrada_af.loc[entrada_af['Diferença'] == 0, 'Situação'] = 'IGUAL'

qtd_iguais = int((entrada_af['Situação'] == 'IGUAL').sum())
qtd_diferentes = int((entrada_af['Situação'] == 'DIFERENTE').sum())

display(Markdown(f'### {qtd_iguais} igual(is) e {qtd_diferentes} diferente(s) de {len(entrada_af)} OPs'))
display(entrada_af)

### 21 igual(is) e 0 diferente(s) de 21 OPs

Entradas / Perdas,Perdas Recozimento,Qtd Entrada AF,Qtd Entrada Recoz.,Entrada AF calculada,Diferença,Situação
Ordem Producao,,,,,,
198135,-3211,201815,205026,201815,0,IGUAL
198176,-620,12308,12928,12308,0,IGUAL
198456,-1628,31329,32957,31329,0,IGUAL
198546,-4822,103093,107915,103093,0,IGUAL
198567,-1054,16067,17121,16067,0,IGUAL
198592,-2257,64455,66712,64455,0,IGUAL
198594,-1651,20152,21803,20152,0,IGUAL
198613,-3994,256419,260413,256419,0,IGUAL
198618,-3186,162478,165664,162478,0,IGUAL
198639,54,338273,338219,338273,0,IGUAL
198645,319,235823,235504,235823,0,IGUAL
198658,-3828,37695,41523,37695,0,IGUAL
198659,-1687,290537,292224,290537,0,IGUAL
198660,-3599,30342,33941,30342,0,IGUAL
198663,-253,6377,6630,6377,0,IGUAL
198693,11513,36386,24873,36386,0,IGUAL
198694,-15979,157925,173904,157925,0,IGUAL
198698,-10237,62248,72485,62248,0,IGUAL
198701,-2422,4988,7410,4988,0,IGUAL
198704,-6481,18232,24713,18232,0,IGUAL
198707,-849,8838,9687,8838,0,IGUAL

## Validando calculo de "Perdas total AF"

In [10]:
# essa analise consiste em validar se a Perdas Total AF realmente esta correta
# Perdas Total AF = Perdas EM + Perdas EA
# importante fazer essa analise pois Raphael ja comunicou que "Perdas EM" devo desconsiderar, mas antes quero analisar pois ela eh uma perda

# uma linha por OP com as tres zonas do acabamento final
perdas_af = df_perdas_tratadas[
    df_perdas_tratadas['Entradas / Perdas'].isin(['Perdas EA', 'Perdas EM', 'Perdas total AF'])
].pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# somando as duas perdas para comparar com o total que veio na base
perdas_af['Total AF calculado'] = perdas_af['Perdas EA'] + perdas_af['Perdas EM']
perdas_af['Diferença'] = perdas_af['Perdas total AF'] - perdas_af['Total AF calculado']

perdas_af['Situação'] = 'DIFERENTE'
perdas_af.loc[perdas_af['Diferença'] == 0, 'Situação'] = 'IGUAL'

qtd_iguais = int((perdas_af['Situação'] == 'IGUAL').sum())
qtd_diferentes = int((perdas_af['Situação'] == 'DIFERENTE').sum())

display(Markdown(f'### {qtd_iguais} igual(is) e {qtd_diferentes} diferente(s) de {len(perdas_af)} OPs'))
display(perdas_af)

### 21 igual(is) e 0 diferente(s) de 21 OPs

Entradas / Perdas,Perdas EA,Perdas EM,Perdas total AF,Total AF calculado,Diferença,Situação
Ordem Producao,,,,,,
198135,-16061,646,-15415,-15415,0,IGUAL
198176,0,-1598,-1598,-1598,0,IGUAL
198456,-2097,-1372,-3469,-3469,0,IGUAL
198546,-4483,-11890,-16373,-16373,0,IGUAL
198567,-1679,-548,-2227,-2227,0,IGUAL
198592,-7922,-5083,-13005,-13005,0,IGUAL
198594,0,-6568,-6568,-6568,0,IGUAL
198613,-49021,-7718,-56739,-56739,0,IGUAL
198618,-7695,-739,-8434,-8434,0,IGUAL
198639,-8104,-3325,-11429,-11429,0,IGUAL
198645,-7179,-11024,-18203,-18203,0,IGUAL
198658,-1808,-3262,-5070,-5070,0,IGUAL
198659,-7728,955,-6773,-6773,0,IGUAL
198660,-951,-5319,-6270,-6270,0,IGUAL
198663,-979,7382,6403,6403,0,IGUAL
198693,0,34392,34392,34392,0,IGUAL
198694,-20333,-8372,-28705,-28705,0,IGUAL
198698,-20759,31,-20728,-20728,0,IGUAL
198701,-878,-1710,-2588,-2588,0,IGUAL
198704,-2092,-4140,-6232,-6232,0,IGUAL
198707,-393,195,-198,-198,0,IGUAL

## Validando calculo da entrada "Qtd Empacotado"

In [11]:
# essa analise consiste em validar se a Qtd Empacotado realmente esta correta
# Qtd Empacotado = Qtd Entrada AF + (Perdas EA + Perdas EM)

# uma linha por OP com as zonas que entram nesse calculo
empacotado = df_perdas_tratadas[
    df_perdas_tratadas['Entradas / Perdas'].isin([
        'Qtd Entrada AF',
        'Perdas EA',
        'Perdas EM',
        'Qtd Empacotado',
    ])
].pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# refazendo a conta para comparar com o valor que veio na base
empacotado['Empacotado calculado'] = (
    empacotado['Qtd Entrada AF'] + empacotado['Perdas EA'] + empacotado['Perdas EM']
)
empacotado['Diferença'] = empacotado['Qtd Empacotado'] - empacotado['Empacotado calculado']

empacotado['Situação'] = 'DIFERENTE'
empacotado.loc[empacotado['Diferença'] == 0, 'Situação'] = 'IGUAL'

qtd_iguais = int((empacotado['Situação'] == 'IGUAL').sum())
qtd_diferentes = int((empacotado['Situação'] == 'DIFERENTE').sum())

display(Markdown(f'### {qtd_iguais} igual(is) e {qtd_diferentes} diferente(s) de {len(empacotado)} OPs'))
display(empacotado)

### 20 igual(is) e 1 diferente(s) de 21 OPs

Entradas / Perdas,Perdas EA,Perdas EM,Qtd Empacotado,Qtd Entrada AF,Empacotado calculado,Diferença,Situação
Ordem Producao,,,,,,,
198135,-16061,646,186400,201815,186400,0,IGUAL
198176,0,-1598,10710,12308,10710,0,IGUAL
198456,-2097,-1372,27860,31329,27860,0,IGUAL
198546,-4483,-11890,86720,103093,86720,0,IGUAL
198567,-1679,-548,13840,16067,13840,0,IGUAL
198592,-7922,-5083,51450,64455,51450,0,IGUAL
198594,0,-6568,13584,20152,13584,0,IGUAL
198613,-49021,-7718,199680,256419,199680,0,IGUAL
198618,-7695,-739,154044,162478,154044,0,IGUAL
198639,-8104,-3325,326844,338273,326844,0,IGUAL
198645,-7179,-11024,217620,235823,217620,0,IGUAL
198658,-1808,-3262,32625,37695,32625,0,IGUAL
198659,-7728,955,283764,290537,283764,0,IGUAL
198660,-951,-5319,24072,30342,24072,0,IGUAL
198663,-979,7382,12780,6377,12780,0,IGUAL
198693,0,34392,34392,36386,70778,-36386,DIFERENTE
198694,-20333,-8372,129220,157925,129220,0,IGUAL
198698,-20759,31,41520,62248,41520,0,IGUAL
198701,-878,-1710,2400,4988,2400,0,IGUAL
198704,-2092,-4140,12000,18232,12000,0,IGUAL
198707,-393,195,8640,8838,8640,0,IGUAL

## Visualizando perdas por OP

Neste caso, essa analise serve para validar tratamento aplicado em df_perdas_tratadas. Se nao retornar nenhum aviso, tratamento esta correto

In [12]:
'''# um display do df_perdas_tratadas filtrado para cada OP, na ordem em que aparecem na base
for op in df_perdas_tratadas['Ordem Producao'].unique():
    df_op = df_perdas_tratadas[df_perdas_tratadas['Ordem Producao'] == op]

    display(Markdown(f'### OP {op}'))
    display(df_op)
    print()'''

# Valores de "Entradas / Perdas" que podem possuir Qtd Frascos positiva
entradas_perdas_ignoradas = [
    "%Gotas cortadas",
    "%Entrada Recozi.",
    "%Entrada AF",
    "%Empacotado",
    "Qtd Gotas Cortadas",
    "Qtd Entrada Recoz.",
    "Qtd Entrada AF",
    "Qtd Empacotado"
]

# Garantindo que Qtd Frascos seja numérico
df_perdas_tratadas["Qtd Frascos"] = pd.to_numeric(
    df_perdas_tratadas["Qtd Frascos"],
    errors="coerce"
)

# Um display do df_perdas_tratadas filtrado para cada OP, na ordem em que aparecem na base
for op in df_perdas_tratadas["Ordem Producao"].unique():

    df_op = df_perdas_tratadas[df_perdas_tratadas["Ordem Producao"] == op]

    display(Markdown(f"### OP {op}"))
    display(df_op)

    # Verificando Entradas / Perdas que deveriam ser negativas,
    # mas possuem Qtd Frascos positiva
    inconsistencias = df_op[
        (~df_op["Entradas / Perdas"].isin(entradas_perdas_ignoradas))
        &
        (df_op["Qtd Frascos"] > 0)
    ]

    if not inconsistencias.empty:

        display(
            Markdown(
                "#### ⚠️ Perdas com Qtd Frascos positiva"
            )
        )

        display(
            inconsistencias[
                ["Entradas / Perdas", "Qtd Frascos"]
            ]
        )

    print()

### OP 198618

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
12,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Qtd Gotas Cortadas,173055
13,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Qtd Entrada Recoz.,165664
14,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Qtd Entrada AF,162478
15,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Qtd Empacotado,154044
16,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Paradas de seção,-1152
17,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas seções rejeito,-1294
18,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas Total AQ,-7391
19,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas Maq-Rec,-4945
20,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas Recozimento,-3186
21,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas EM,-739
22,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas EA,-7695
23,2026-08-10 00:00:00,A,A1,SB -1035-SWN,198618,Perdas total AF,-8434

### OP 198698

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
36,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Qtd Gotas Cortadas,124012
37,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Qtd Entrada Recoz.,72485
38,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Qtd Entrada AF,62248
39,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Qtd Empacotado,41520
40,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Paradas de seção,-10738
41,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas seções rejeito,-7826
42,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas Total AQ,-51527
43,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas Maq-Rec,-32963
44,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas Recozimento,-10237
45,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas EM,31
46,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas EA,-20759
47,2026-08-10 00:00:00,A,A2,SB -1036-SWN,198698,Perdas total AF,-20728

#### ⚠️ Perdas com Qtd Frascos positiva

1  Entradas / Perdas  Qtd Frascos
45         Perdas EM           31

### OP 198567

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
60,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Qtd Gotas Cortadas,18238
61,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Qtd Entrada Recoz.,17121
62,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Qtd Entrada AF,16067
63,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Qtd Empacotado,13840
64,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Paradas de seção,-586
65,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas seções rejeito,-474
66,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas Total AQ,-1117
67,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas Maq-Rec,-57
68,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas Recozimento,-1054
69,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas EM,-548
70,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas EA,-1679
71,2026-08-10 00:00:00,A,A2,SB -1037-SWN,198567,Perdas total AF,-2227

### OP 198135

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
84,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Qtd Gotas Cortadas,213230
85,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Qtd Entrada Recoz.,205026
86,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Qtd Entrada AF,201815
87,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Qtd Empacotado,186400
88,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Paradas de seção,-1708
89,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas seções rejeito,-4260
90,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas Total AQ,-8204
91,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas Maq-Rec,-2236
92,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas Recozimento,-3211
93,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas EM,646
94,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas EA,-16061
95,2026-08-10 00:00:00,A,A3,SB -1036-SWN,198135,Perdas total AF,-15415

#### ⚠️ Perdas com Qtd Frascos positiva

1  Entradas / Perdas  Qtd Frascos
93         Perdas EM          646

### OP 198659

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
108,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Qtd Gotas Cortadas,302415
109,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Qtd Entrada Recoz.,292224
110,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Qtd Entrada AF,290537
111,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Qtd Empacotado,283764
112,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Paradas de seção,-1221
113,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas seções rejeito,-4310
114,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas Total AQ,-10191
115,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas Maq-Rec,-4660
116,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas Recozimento,-1687
117,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas EM,955
118,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas EA,-7728
119,2026-08-10 00:00:00,A,A4,SB -1348-S,198659,Perdas total AF,-6773

#### ⚠️ Perdas com Qtd Frascos positiva

1   Entradas / Perdas  Qtd Frascos
117         Perdas EM          955

### OP 198639

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
132,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Qtd Gotas Cortadas,348048
133,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Qtd Entrada Recoz.,338219
134,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Qtd Entrada AF,338273
135,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Qtd Empacotado,326844
136,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Paradas de seção,-1904
137,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas seções rejeito,-1093
138,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas Total AQ,-9829
139,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas Maq-Rec,-6832
140,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas Recozimento,54
141,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas EM,-3325
142,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas EA,-8104
143,2026-08-10 00:00:00,A,A5,SB -1290-S,198639,Perdas total AF,-11429

#### ⚠️ Perdas com Qtd Frascos positiva

1     Entradas / Perdas  Qtd Frascos
140  Perdas Recozimento           54

### OP 198645

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
156,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Qtd Gotas Cortadas,244368
157,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Qtd Entrada Recoz.,235504
158,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Qtd Entrada AF,235823
159,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Qtd Empacotado,217620
160,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Paradas de seção,-2346
161,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas seções rejeito,-8864
162,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas Total AQ,-8864
163,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas Maq-Rec,2346
164,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas Recozimento,319
165,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas EM,-11024
166,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas EA,-7179
167,2026-08-10 00:00:00,A,A6,SB -1579-N1N,198645,Perdas total AF,-18203

#### ⚠️ Perdas com Qtd Frascos positiva

1     Entradas / Perdas  Qtd Frascos
163      Perdas Maq-Rec         2346
164  Perdas Recozimento          319

### OP 198701

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
180,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Qtd Gotas Cortadas,8745
181,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Qtd Entrada Recoz.,7410
182,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Qtd Entrada AF,4988
183,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Qtd Empacotado,2400
184,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Paradas de seção,-34
185,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas seções rejeito,0
186,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas Total AQ,-1335
187,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas Maq-Rec,-1301
188,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas Recozimento,-2422
189,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas EM,-1710
190,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas EA,-878
191,2026-08-10 00:00:00,B,B1,LB -0449-SX,198701,Perdas total AF,-2588

### OP 198704

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
204,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Qtd Gotas Cortadas,27721
205,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Qtd Entrada Recoz.,24713
206,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Qtd Entrada AF,18232
207,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Qtd Empacotado,12000
208,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Paradas de seção,-445
209,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas seções rejeito,0
210,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas Total AQ,-3008
211,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas Maq-Rec,-2563
212,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas Recozimento,-6481
213,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas EM,-4140
214,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas EA,-2092
215,2026-08-10 00:00:00,B,B1,LB -0449-SX,198704,Perdas total AF,-6232

### OP 198707

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
228,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Qtd Gotas Cortadas,11054
229,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Qtd Entrada Recoz.,9687
230,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Qtd Entrada AF,8838
231,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Qtd Empacotado,8640
232,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Paradas de seção,-21
233,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas seções rejeito,0
234,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas Total AQ,-1367
235,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas Maq-Rec,-1346
236,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas Recozimento,-849
237,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas EM,195
238,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas EA,-393
239,2026-08-10 00:00:00,B,B1,LB -0449-SX,198707,Perdas total AF,-198

#### ⚠️ Perdas com Qtd Frascos positiva

1   Entradas / Perdas  Qtd Frascos
237         Perdas EM          195

### OP 198693

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
252,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Qtd Gotas Cortadas,43187
253,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Qtd Entrada Recoz.,24873
254,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Qtd Entrada AF,36386
255,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Qtd Empacotado,34392
256,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Paradas de seção,-17592
257,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas seções rejeito,0
258,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas Total AQ,-18314
259,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas Maq-Rec,-722
260,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas Recozimento,11513
261,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas EM,34392
262,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas EA,0
263,2026-08-10 00:00:00,B,B6,PL -5814-,198693,Perdas total AF,34392

#### ⚠️ Perdas com Qtd Frascos positiva

1     Entradas / Perdas  Qtd Frascos
260  Perdas Recozimento        11513
261           Perdas EM        34392
263     Perdas total AF        34392

### OP 198694

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
276,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Qtd Gotas Cortadas,190094
277,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Qtd Entrada Recoz.,173904
278,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Qtd Entrada AF,157925
279,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Qtd Empacotado,129220
280,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Paradas de seção,-2648
281,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas seções rejeito,-8403
282,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas Total AQ,-16190
283,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas Maq-Rec,-5139
284,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas Recozimento,-15979
285,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas EM,-8372
286,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas EA,-20333
287,2026-08-10 00:00:00,B,B2,SB -1704-S,198694,Perdas total AF,-28705

### OP 198663

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
300,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Qtd Gotas Cortadas,7050
301,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Qtd Entrada Recoz.,6630
302,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Qtd Entrada AF,6377
303,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Qtd Empacotado,12780
304,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Paradas de seção,-891
305,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas seções rejeito,-91
306,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas Total AQ,-420
307,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas Maq-Rec,562
308,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas Recozimento,-253
309,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas EM,7382
310,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas EA,-979
311,2026-08-10 00:00:00,B,B5,SB -0019-N1D,198663,Perdas total AF,6403

#### ⚠️ Perdas com Qtd Frascos positiva

1   Entradas / Perdas  Qtd Frascos
307    Perdas Maq-Rec          562
309         Perdas EM         7382
311   Perdas total AF         6403

### OP 198613

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
324,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Qtd Gotas Cortadas,335751
325,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Qtd Entrada Recoz.,260413
326,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Qtd Entrada AF,256419
327,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Qtd Empacotado,199680
328,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Paradas de seção,-77613
329,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas seções rejeito,-5089
330,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas Total AQ,-75338
331,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas Maq-Rec,7364
332,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas Recozimento,-3994
333,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas EM,-7718
334,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas EA,-49021
335,2026-08-10 00:00:00,B,B5,SB -1471-SN,198613,Perdas total AF,-56739

#### ⚠️ Perdas com Qtd Frascos positiva

1   Entradas / Perdas  Qtd Frascos
331    Perdas Maq-Rec         7364

### OP 198546

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
348,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Qtd Gotas Cortadas,118190
349,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Qtd Entrada Recoz.,107915
350,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Qtd Entrada AF,103093
351,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Qtd Empacotado,86720
352,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Paradas de seção,-1244
353,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas seções rejeito,-3587
354,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas Total AQ,-10275
355,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas Maq-Rec,-5444
356,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas Recozimento,-4822
357,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas EM,-11890
358,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas EA,-4483
359,2026-08-10 00:00:00,B,B7,MB -1585-S,198546,Perdas total AF,-16373

### OP 198658

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
372,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Qtd Gotas Cortadas,46079
373,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Qtd Entrada Recoz.,41523
374,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Qtd Entrada AF,37695
375,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Qtd Empacotado,32625
376,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Paradas de seção,-233
377,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas seções rejeito,-2293
378,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas Total AQ,-4556
379,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas Maq-Rec,-2030
380,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas Recozimento,-3828
381,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas EM,-3262
382,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas EA,-1808
383,2026-08-10 00:00:00,B,B3,LB -0502-S,198658,Perdas total AF,-5070

### OP 198592

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
396,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Qtd Gotas Cortadas,74848
397,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Qtd Entrada Recoz.,66712
398,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Qtd Entrada AF,64455
399,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Qtd Empacotado,51450
400,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Paradas de seção,-546
401,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas seções rejeito,-3208
402,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas Total AQ,-8136
403,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas Maq-Rec,-4382
404,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas Recozimento,-2257
405,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas EM,-5083
406,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas EA,-7922
407,2026-08-10 00:00:00,1,12,MB -1512-SN,198592,Perdas total AF,-13005

### OP 198176

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
420,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Qtd Gotas Cortadas,17272
421,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Qtd Entrada Recoz.,12928
422,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Qtd Entrada AF,12308
423,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Qtd Empacotado,10710
424,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Paradas de seção,-4032
425,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas seções rejeito,0
426,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas Total AQ,-4344
427,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas Maq-Rec,-312
428,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas Recozimento,-620
429,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas EM,-1598
430,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas EA,0
431,2026-08-10 00:00:00,1,14,LB -0478-N1,198176,Perdas total AF,-1598

### OP 198456

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
444,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Qtd Gotas Cortadas,44651
445,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Qtd Entrada Recoz.,32957
446,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Qtd Entrada AF,31329
447,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Qtd Empacotado,27860
448,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Paradas de seção,-8297
449,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas seções rejeito,-2171
450,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas Total AQ,-11694
451,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas Maq-Rec,-1226
452,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas Recozimento,-1628
453,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas EM,-1372
454,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas EA,-2097
455,2026-08-10 00:00:00,1,15,LB -0491-N1,198456,Perdas total AF,-3469

### OP 198594

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
468,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Qtd Gotas Cortadas,23039
469,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Qtd Entrada Recoz.,21803
470,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Qtd Entrada AF,20152
471,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Qtd Empacotado,13584
472,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Paradas de seção,-38
473,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas seções rejeito,-532
474,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas Total AQ,-1236
475,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas Maq-Rec,-666
476,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas Recozimento,-1651
477,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas EM,-6568
478,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas EA,0
479,2026-08-10 00:00:00,1,10,MB -1398-S,198594,Perdas total AF,-6568

### OP 198660

1,Data Wheaton (dia),Forno,Maquina,Prefixo,Ordem Producao,Entradas / Perdas,Qtd Frascos
492,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Qtd Gotas Cortadas,37567
493,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Qtd Entrada Recoz.,33941
494,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Qtd Entrada AF,30342
495,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Qtd Empacotado,24072
496,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Paradas de seção,-1014
497,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas seções rejeito,-2086
498,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Total AQ,-3626
499,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Maq-Rec,-526
500,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas Recozimento,-3599
501,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EM,-5319
502,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas EA,-951
503,2026-08-10 00:00:00,1,11,LB -0586-S,198660,Perdas total AF,-6270

## Recalculando zonas de entradas (incluir isso futuramente em "Tratamentos")

In [13]:
'''# recalculando as zonas de entrada a partir das perdas ja tratadas
# Qtd Entrada Recoz. = Qtd Gotas Cortadas + (Paradas de seção + Perdas seções rejeito + Perdas Maq-Rec)
# Qtd Entrada AF     = Qtd Entrada Recoz. + Perdas Recozimento
# Qtd Empacotado     = Qtd Entrada AF + (Perdas EA + Perdas EM)

# guardando os valores atuais so para contar quantos serao alterados
qtd_frascos_antes = df_perdas_tratadas['Qtd Frascos'].copy()

# visao larga (uma linha por OP) para aplicar as formulas
zonas_op = df_perdas_tratadas.pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# a ordem importa: cada entrada usa a entrada anterior ja recalculada
zonas_op['Qtd Entrada Recoz.'] = (
    zonas_op['Qtd Gotas Cortadas']
    + zonas_op['Paradas de seção']
    + zonas_op['Perdas seções rejeito']
    + zonas_op['Perdas Maq-Rec']
)
zonas_op['Qtd Entrada AF'] = zonas_op['Qtd Entrada Recoz.'] + zonas_op['Perdas Recozimento']
zonas_op['Qtd Empacotado'] = zonas_op['Qtd Entrada AF'] + zonas_op['Perdas EA'] + zonas_op['Perdas EM']

# devolvendo os valores recalculados para o df em formato longo
# 'Qtd Gotas Cortadas' nao entra: e a origem da cascata, nao tem calculo
entradas_recalculadas = ['Qtd Entrada Recoz.', 'Qtd Entrada AF', 'Qtd Empacotado']

for zona in entradas_recalculadas:
    linhas_zona = df_perdas_tratadas['Entradas / Perdas'] == zona
    df_perdas_tratadas.loc[linhas_zona, 'Qtd Frascos'] = (
        df_perdas_tratadas.loc[linhas_zona, 'Ordem Producao'].map(zonas_op[zona])
    )

qtd_alterados = int((df_perdas_tratadas['Qtd Frascos'] != qtd_frascos_antes).sum())
print(f'{qtd_alterados} valor(es) de entrada recalculado(s)')'''

"# recalculando as zonas de entrada a partir das perdas ja tratadas\n# Qtd Entrada Recoz. = Qtd Gotas Cortadas + (Paradas de seção + Perdas seções rejeito + Perdas Maq-Rec)\n# Qtd Entrada AF     = Qtd Entrada Recoz. + Perdas Recozimento\n# Qtd Empacotado     = Qtd Entrada AF + (Perdas EA + Perdas EM)\n\n# guardando os valores atuais so para contar quantos serao alterados\nqtd_frascos_antes = df_perdas_tratadas['Qtd Frascos'].copy()\n\n# visao larga (uma linha por OP) para aplicar as formulas\nzonas_op = df_perdas_tratadas.pivot_table(\n    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'\n)\n\n# a ordem importa: cada entrada usa a entrada anterior ja recalculada\nzonas_op['Qtd Entrada Recoz.'] = (\n    zonas_op['Qtd Gotas Cortadas']\n    + zonas_op['Paradas de seção']\n    + zonas_op['Perdas seções rejeito']\n    + zonas_op['Perdas Maq-Rec']\n)\nzonas_op['Qtd Entrada AF'] = zonas_op['Qtd Entrada Recoz.'] + zonas_op['Perdas Recozimento']\nzonas_op['Qtd Empacotado'] = zonas_op['Qtd Entrada AF'] + zonas_op['Perdas EA'] + zonas_op['Perdas EM']\n\n# devolvendo os valores recalculados para o df em formato longo\n# 'Qtd Gotas Cortadas' nao entra: e a origem da cascata, nao tem calculo\nentradas_recalculadas = ['Qtd Entrada Recoz.', 'Qtd Entrada AF', 'Qtd Empacotado']\n\nfor zona in entradas_recalculadas:\n    linhas_zona = df_perdas_tratadas['Entradas / Perdas'] == zona\n    df_perdas_tratadas.loc[linhas_zona, 'Qtd Frascos'] = (\n        df_perdas_tratadas.loc[linhas_zona, 'Ordem Producao'].map(zonas_op[zona])\n    )\n\nqtd_alterados = int((df_perdas_tratadas['Qtd Frascos'] != qtd_frascos_antes).sum())\nprint(f'{qtd_alterados} valor(es) de entrada recalculado(s)')"

## Grafico de cascata

In [14]:
# grafico 1: cascata (waterfall), um plot para cada OP do dataframe
# obs: o plotly.express nao tem waterfall, esse tipo so existe no graph_objects (go)

# os valores sao plotados exatamente como vieram da base, sem nenhum tratamento

# visao larga (uma linha por OP)
# 'Perdas Total AQ' e 'Perdas total AF' ficam de fora por serem subtotais das perdas
# individuais: se entrassem, a mesma perda apareceria duas vezes na cascata
qtd_op = df_perdas_tratadas.pivot_table(
    index='Ordem Producao', columns='Entradas / Perdas', values='Qtd Frascos', aggfunc='sum'
)

# cada etapa com o seu papel na cascata:
#   absolute = valor lido direto da base | relative = variacao somada ao acumulado
# os pontos de medicao usam 'absolute' para que a barra mostre o valor gravado na base,
# e nao a soma que o plotly calcularia por conta propria
etapas_cascata = [
    ('Qtd Gotas Cortadas', 'absolute'),
    ('Paradas de seção', 'relative'),
    ('Perdas seções rejeito', 'relative'),
    ('Perdas Maq-Rec', 'relative'),
    ('Qtd Entrada Recoz.', 'absolute'),
    ('Perdas Recozimento', 'relative'),
    ('Qtd Entrada AF', 'absolute'),
    ('Perdas EA', 'relative'),
    ('Perdas EM', 'relative'),
    ('Qtd Empacotado', 'absolute'),
]

etapas = [etapa for etapa, _ in etapas_cascata]
medidas = [medida for _, medida in etapas_cascata]

for op in qtd_op.index:
    valores = [qtd_op.loc[op, etapa] for etapa in etapas]

    display(Markdown(f'### OP {op}'))

    fig = go.Figure(go.Waterfall(
        orientation='v',
        measure=medidas,
        x=etapas,
        y=valores,
        text=[f'{valor:,.0f}'.replace(',', '.') for valor in valores],
        textposition='outside',
        connector={'line': {'color': '#8a8a85', 'dash': 'dot', 'width': 1}},
        decreasing={'marker': {'color': '#e34948'}},
        increasing={'marker': {'color': '#2a78d6'}},
        totals={'marker': {'color': '#2a78d6'}},
    ))

    fig.update_layout(
        title=f'Cascata de perdas ao longo do processo — OP {op}',
        xaxis_title='Etapa do processo',
        yaxis_title='Qtd Frascos',
        template='plotly_white',
        showlegend=False,
        height=460,
    )

    fig.show()
    print()

### OP 198135

### OP 198176

### OP 198456

### OP 198546

### OP 198567

### OP 198592

### OP 198594

### OP 198613

### OP 198618

### OP 198639

### OP 198645

### OP 198658

### OP 198659

### OP 198660

### OP 198663

### OP 198693

### OP 198694

### OP 198698

### OP 198701

### OP 198704

### OP 198707

## Validando % empacotado entre as bases Zonas e Perdas e Desempenho de empacotamento

In [15]:
# comparando o % empacotado por OP entre as duas bases

# a base de desempenho traz o percentual em fracao (0.87 = 87%), por isso o *100
desempenho_pct = df_desemp_emp_diario.set_index('OP Vertech')['Empacotado %'] * 100
desempenho_pct.index = desempenho_pct.index.astype(str)

# na base de zonas o percentual e calculado: (Qtd Empacotado / Qtd Gotas Cortadas) * 100
zonas_pct = qtd_op['Qtd Empacotado'] / qtd_op['Qtd Gotas Cortadas'] * 100

# OPs que nao existem nas duas bases nao tem como ser comparadas
so_em_zonas = qtd_op.index.difference(desempenho_pct.index)
so_em_desempenho = desempenho_pct.index.difference(qtd_op.index)

comparacao = pd.DataFrame({
    '% Empacotado (Zonas e Perdas)': zonas_pct,
    '% Empacotado (Desempenho)': desempenho_pct,
})
comparacao.index.name = 'Ordem Producao'
comparacao['Diferença (pp)'] = (
    comparacao['% Empacotado (Zonas e Perdas)'] - comparacao['% Empacotado (Desempenho)']
)

# tolerancia em pontos percentuais, para absorver arredondamento entre os sistemas
tolerancia_pp = 0.1

comparacao['Situação'] = 'DIVERGENTE'
comparacao.loc[comparacao['Diferença (pp)'].abs() <= tolerancia_pp, 'Situação'] = 'IGUAL'
comparacao.loc[comparacao['Diferença (pp)'].isna(), 'Situação'] = 'SEM PAR'

# maiores divergencias primeiro
comparacao = comparacao.sort_values('Diferença (pp)', key=abs, ascending=False).round(2)

qtd_iguais = int((comparacao['Situação'] == 'IGUAL').sum())
qtd_divergentes = int((comparacao['Situação'] == 'DIVERGENTE').sum())

display(Markdown(
    f'### {qtd_iguais} igual(is) e {qtd_divergentes} divergente(s) de {len(comparacao)} OPs '
    f'(tolerancia de {tolerancia_pp} pp)'
))
display(comparacao)
print()

if len(so_em_zonas) or len(so_em_desempenho):
    display(Markdown('### OPs sem par entre as bases'))
    display(pd.DataFrame({
        'Ordem Producao': list(so_em_zonas) + list(so_em_desempenho),
        'Presente apenas em': ['Zonas e Perdas'] * len(so_em_zonas) + ['Desempenho'] * len(so_em_desempenho),
    }))
    print()

### 7 igual(is) e 14 divergente(s) de 21 OPs (tolerancia de 0.1 pp)

,% Empacotado (Zonas e Perdas),% Empacotado (Desempenho),Diferença (pp),Situação
Ordem Producao,,,,
198663,181.28,94.67,86.61,DIVERGENTE
198456,62.40,77.39,-14.99,DIVERGENTE
198701,27.44,38.94,-11.50,DIVERGENTE
198707,78.16,69.22,8.95,DIVERGENTE
198693,79.64,87.13,-7.49,DIVERGENTE
198645,89.05,92.88,-3.83,DIVERGENTE
198567,75.89,79.63,-3.74,DIVERGENTE
198704,43.29,46.93,-3.64,DIVERGENTE
198694,67.98,65.40,2.57,DIVERGENTE
198613,59.47,61.05,-1.58,DIVERGENTE
198660,64.08,64.29,-0.22,DIVERGENTE
198698,33.48,33.27,0.21,DIVERGENTE
198618,89.01,89.15,-0.13,DIVERGENTE
198639,93.91,93.79,0.12,DIVERGENTE
198546,73.37,73.28,0.09,IGUAL
198135,87.42,87.46,-0.05,IGUAL
198592,68.74,68.71,0.03,IGUAL
198176,62.01,61.98,0.03,IGUAL
198659,93.83,93.84,-0.00,IGUAL
198594,58.96,58.96,0.00,IGUAL
198658,70.80,70.80,0.00,IGUAL

In [16]:
# histograma da diferenca de % empacotado por OP entre as duas bases
# diferenca = (% empacotado em Zonas e Perdas) - (% empacotado em Desempenho)
# valor negativo significa que a base de Zonas reporta menos empacotado que a de Desempenho

diferencas_hist = (zonas_pct - desempenho_pct).dropna()

diferencas_hist_df = diferencas_hist.reset_index()
diferencas_hist_df.columns = ['Ordem Producao', 'Diferença (pp)']

# ordem crescente pela diferenca, das maiores divergencias negativas as positivas
diferencas_hist_df = diferencas_hist_df.sort_values('Diferença (pp)').reset_index(drop=True)

fig = px.histogram(
    diferencas_hist_df,
    x='Diferença (pp)',
    title='Distribuição da diferença de % empacotado entre as bases',
    template='plotly_white',
    height=460,
)

# faixas de X pp: com 21 OPs, e a largura que separa o grosso dos dados dos casos extremos
fig.update_traces(
    xbins={'size': 2},
    marker={'color': '#2a78d6', 'line': {'color': '#fcfcfb', 'width': 2}},
)

# referencia no zero, onde as duas bases concordariam
fig.add_vline(
    x=0, line_dash='dot', line_color='#e34948',
    annotation_text='Nenhuma diferença (diff = 0)', annotation_position='top',
)

fig.update_layout(
    xaxis_title='Diferença (pontos percentuais)',
    yaxis_title='Quantidade de OPs',
    bargap=0.05,
)

display(diferencas_hist_df)

fig.show()

   Ordem Producao  Diferença (pp)
0          198456      -14.993870
1          198701      -11.495140
2          198693       -7.491468
3          198645       -3.825689
4          198567       -3.744116
5          198704       -3.636652
6          198613       -1.580373
7          198660       -0.217357
8          198618       -0.131358
9          198135       -0.045120
10         198659       -0.004654
11         198658        0.001537
12         198594        0.002559
13         198176        0.028707
14         198592        0.029376
15         198546        0.094249
16         198639        0.116415
17         198698        0.210790
18         198694        2.572855
19         198707        8.945782
20         198663       86.609929

In [17]:
# comparando o % empacotado por OP entre as duas bases, com a tolerancia definida
# pela analise da distribuicao: o bloco compacto de OPs vai ate 0,22 pp e o proximo
# valor so aparece em 0,64 pp, entao o corte em 0,25 pp fecha esse bloco

# reaproveitando desempenho_pct e zonas_pct ja calculados acima
comparacao_tolerancia = pd.DataFrame({
    '% Empacotado (Zonas e Perdas)': zonas_pct,
    '% Empacotado (Desempenho)': desempenho_pct,
})
comparacao_tolerancia.index.name = 'Ordem Producao'
comparacao_tolerancia['Diferença (pp)'] = (
    comparacao_tolerancia['% Empacotado (Zonas e Perdas)']
    - comparacao_tolerancia['% Empacotado (Desempenho)']
)

# tolerancia em pontos percentuais: 0.25 significa a faixa de -0,25 pp a +0,25 pp
tolerancia_pp = 0.25

comparacao_tolerancia['Situação'] = 'DIVERGENTE'
comparacao_tolerancia.loc[
    comparacao_tolerancia['Diferença (pp)'].abs() <= tolerancia_pp, 'Situação'
] = 'IGUAL'
comparacao_tolerancia.loc[
    comparacao_tolerancia['Diferença (pp)'].isna(), 'Situação'
] = 'SEM PAR'

# maiores divergencias primeiro
comparacao_tolerancia = comparacao_tolerancia.sort_values(
    'Diferença (pp)', key=abs, ascending=False
).round(2)

qtd_iguais = int((comparacao_tolerancia['Situação'] == 'IGUAL').sum())
qtd_divergentes = int((comparacao_tolerancia['Situação'] == 'DIVERGENTE').sum())

display(Markdown(
    f'### {qtd_iguais} igual(is) e {qtd_divergentes} divergente(s) de {len(comparacao_tolerancia)} OPs '
    f'(tolerancia de ±{tolerancia_pp} pp)'
))
display(comparacao_tolerancia)
print()

if len(so_em_zonas) or len(so_em_desempenho):
    display(Markdown('### OPs sem par entre as bases'))
    display(pd.DataFrame({
        'Ordem Producao': list(so_em_zonas) + list(so_em_desempenho),
        'Presente apenas em': ['Zonas e Perdas'] * len(so_em_zonas) + ['Desempenho'] * len(so_em_desempenho),
    }))
    print()

### 11 igual(is) e 10 divergente(s) de 21 OPs (tolerancia de ±0.25 pp)

,% Empacotado (Zonas e Perdas),% Empacotado (Desempenho),Diferença (pp),Situação
Ordem Producao,,,,
198663,181.28,94.67,86.61,DIVERGENTE
198456,62.40,77.39,-14.99,DIVERGENTE
198701,27.44,38.94,-11.50,DIVERGENTE
198707,78.16,69.22,8.95,DIVERGENTE
198693,79.64,87.13,-7.49,DIVERGENTE
198645,89.05,92.88,-3.83,DIVERGENTE
198567,75.89,79.63,-3.74,DIVERGENTE
198704,43.29,46.93,-3.64,DIVERGENTE
198694,67.98,65.40,2.57,DIVERGENTE
198613,59.47,61.05,-1.58,DIVERGENTE
198660,64.08,64.29,-0.22,IGUAL
198698,33.48,33.27,0.21,IGUAL
198618,89.01,89.15,-0.13,IGUAL
198639,93.91,93.79,0.12,IGUAL
198546,73.37,73.28,0.09,IGUAL
198135,87.42,87.46,-0.05,IGUAL
198592,68.74,68.71,0.03,IGUAL
198176,62.01,61.98,0.03,IGUAL
198659,93.83,93.84,-0.00,IGUAL
198594,58.96,58.96,0.00,IGUAL
198658,70.80,70.80,0.00,IGUAL

## Representatividade das OPs divergentes

In [18]:
# representatividade das OPs divergentes: peso na contagem e no volume produzido
# contar OPs trata uma ordem de 7 mil frascos igual a uma de 340 mil, por isso
# olhamos tambem a participacao em Gotas Cortadas

gotas_por_op = qtd_op['Qtd Gotas Cortadas']

representatividade = pd.DataFrame({
    'Situação': comparacao_tolerancia['Situação'],
    'Gotas Cortadas': gotas_por_op,
}).dropna()

resumo = representatividade.groupby('Situação')['Gotas Cortadas'].agg(['size', 'sum'])
resumo.columns = ['OPs', 'Gotas Cortadas']

resumo['% das OPs'] = resumo['OPs'] / resumo['OPs'].sum() * 100
resumo['% da produção'] = resumo['Gotas Cortadas'] / resumo['Gotas Cortadas'].sum() * 100

pct_ops = resumo.loc['DIVERGENTE', '% das OPs']
pct_producao = resumo.loc['DIVERGENTE', '% da produção']

display(Markdown(
    f'### As OPs divergentes sao {pct_ops:.0f}% das OPs, mas representam '
    f'{pct_producao:.0f}% da producao do periodo'
))
display(resumo.round(1))

### As OPs divergentes sao 48% das OPs, mas representam 39% da producao do periodo

            OPs  Gotas Cortadas  % das OPs  % da produção
Situação
DIVERGENTE   10          930859       47.6           38.6
IGUAL        11         1477755       52.4           61.4